package com.gmobile.sqliteeditor.orm.dao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_DATA".
 */
public class AppData {

    private Long id;
    private String appName;
    private String appPackageName;
    private Long lastModified;
    private Integer isSystem;

    public AppData() {
    }

    public AppData(Long id) {
        this.id = id;
    }

    public AppData(Long id, String appName, String appPackageName, Long lastModified, Integer isSystem) {
        this.id = id;
        this.appName = appName;
        this.appPackageName = appPackageName;
        this.lastModified = lastModified;
        this.isSystem = isSystem;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppPackageName() {
        return appPackageName;
    }

    public void setAppPackageName(String appPackageName) {
        this.appPackageName = appPackageName;
    }

    public Long getLastModified() {
        return lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    public Integer getIsSystem() {
        return isSystem;
    }

    public void setIsSystem(Integer isSystem) {
        this.isSystem = isSystem;
    }

}
