package com.gmobile.sqliteeditor.orm.dao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.gmobile.sqliteeditor.model.bean.BaseData;

/**
 * Entity mapped to table "HISTORY_DATA".
 */
public class HistoryData{

    private Long id;
    private String name;
    private String path;
    private String appName;
    private String appPackageName;
    private Long size;
    private Long lastModified;
    private Long openTime;

    public HistoryData() {
    }

    public HistoryData(Long id) {
        this.id = id;
    }

    public HistoryData(Long id, String name, String path, String appName, String appPackageName, Long size, Long lastModified, Long openTime) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.appName = appName;
        this.appPackageName = appPackageName;
        this.size = size;
        this.lastModified = lastModified;
        this.openTime = openTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppPackageName() {
        return appPackageName;
    }

    public void setAppPackageName(String appPackageName) {
        this.appPackageName = appPackageName;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getLastModified() {
        return lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    public Long getOpenTime() {
        return openTime;
    }

    public void setOpenTime(Long openTime) {
        this.openTime = openTime;
    }

}
